(define (domain wumpus-domain)
(:requirements :strips)

(:predicates
(at ?what ?sq)
 (adj ?sq-1 ?sq-2)
 (pit ?sq)
 (wumpus-in ?sq)
 (have ?who ?what) 
 (is-agent ?who)
 (is-wumpus ?who)
 (is-gold ?what)
 (is-arrow ?what)
 (is-alive ?who)
 (dead ?who))

(:action move
  :parameters (?who ?from ?to)
  :precondition (and (is-agent ?who)
                     (at ?who ?from)
                     (adj ?from ?to)
                     (not (pit ?to))
                     (not (wumpus-in ?to)))
  :effect (and (not (at ?who ?from))
               (at ?who ?to))
  )

(:action take
  :parameters (?who ?what ?where)
  :precondition (and (is-agent ?who)
                     (at  ?who ?where)
                     (at  ?what ?where))
  :effect (and (have ?who ?what)
               (not  (at ?what ?where)))
  )

(:action shoot
  :parameters (?who ?where ?arrow ?victim ?where-victim)
  :precondition (and (is-alive ?who)
                (have ?who ?arrow)
                (is-arrow ?arrow)
                (at ?who ?where)
                (is-wumpus ?victim)
                (at ?who ?where)
                (is-alive ?victim)
                (at ?victim ?where-victim)
                (adj ?where ?where-victim))
  :effect (and (dead ?victim)
               (not (is-alive ?victim))
               (not (at ?victim ?where-victim))
               (not (have ?who ?arrow)))
  )

)